version 0.7-11

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3042,17 +3042,17 @@ fi
 rm -f gdal_test errors.txt gdal_test.c
 
 
-GDAL_DATA_TEST_FILE="${GDAL_DATADIR}/epsg.wkt"
-echo "$as_me:$LINENO: checking GDAL: ${GDAL_DATADIR}/epsg.wkt readable" >&5
-echo $ECHO_N "checking GDAL: ${GDAL_DATADIR}/epsg.wkt readable... $ECHO_C" >&6
+GDAL_DATA_TEST_FILE="${GDAL_DATADIR}/pcs.csv"
+echo "$as_me:$LINENO: checking GDAL: ${GDAL_DATADIR}/pcs.csv readable" >&5
+echo $ECHO_N "checking GDAL: ${GDAL_DATADIR}/pcs.csv readable... $ECHO_C" >&6
 if test -r "${GDAL_DATA_TEST_FILE}" ; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-  { { echo "$as_me:$LINENO: error: epsg.wkt not found in GDAL data directory." >&5
-echo "$as_me: error: epsg.wkt not found in GDAL data directory." >&2;}
+  { { echo "$as_me:$LINENO: error: pcs.csv not found in GDAL data directory." >&5
+echo "$as_me: error: pcs.csv not found in GDAL data directory." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
