version 0.4-12

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -63,6 +63,14 @@ AC_CHECK_HEADERS(proj_api.h)
 if test "$ac_cv_header_proj_api_h" = "no" ; then
     STOP="stop"
 fi
+if test "$STOP" = "stop" ; then
+    echo "proj_api.h not found."
+    echo "If the PROJ.4 library is installed in a non-standard location,"
+    echo "use --configure-args='--with-proj-include=/opt/local/include'"
+    echo "for example, replacing /opt/local/* with appropriate values"
+    echo "for your installation. If PROJ.4 is not installed, install it."
+    exit 1
+fi
           
 dnl ditto for a library path
 AC_ARG_WITH([proj-lib],
@@ -70,22 +78,20 @@ AC_ARG_WITH([proj-lib],
                [the location of proj libraries]),
                [proj_lib_path=$withval])
 if test [ -n "$proj_lib_path" ] ; then
-    AC_SUBST([PKG_LIBS],[" -L${proj_lib_path} ${PKG_LIBS}"])
+    AC_SUBST([LIBS],[" -L${proj_lib_path} ${LIBS}"])
+    AC_SUBST([PKG_LIBS], [" -L${proj_lib_path} ${PKG_LIBS}"])
 fi
 
-AC_SUBST([LIBS], ["${LIBS} ${PKG_LIBS}"])
-
 AC_CHECK_LIB(proj,pj_init_plus,PROJ_SETTING="external",PROJ_SETTING="none",$LIBS)
-#echo "PROJ_SETTING: $PROJ_SETTING"
+
 if test "$PROJ_SETTING" = "none" ; then
     STOP="stop"
 fi
 if test "$STOP" = "stop" ; then
-    echo "libproj.a and/or proj_api.h not found."
+    echo "libproj.a not found."
     echo "If the PROJ.4 library is installed in a non-standard location,"
-    echo "use --configure-args='--with-proj-include=/opt/local/include"
-    echo "--with-proj-lib=/opt/local/lib' for example, replacing /opt/local/*"
-    echo "with appropriate values for your installation."
+    echo "use --configure-args='--with-proj-lib=/opt/local/lib' for example,"
+    echo "replacing /opt/local/* with appropriate values for your installation."
     echo "If PROJ.4 is not installed, install it."
     exit 1
 fi
